version: "3"
services:
  pg_bookdem:
    image: postgres
    container_name: pg_bookdem
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - volum_pg_bookdem:/var/lib/postgresql/data

  app_node:
    build: .
    container_name: app_node
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - pg_bookdem
    volumes:
      - .:/usr/src
      - /usr/src/node_modules


volumes:
  volum_pg_bookdem:
