version: "3"
services:
  pg_bookdem:
    image: postgres
    container_name: pg_bookdem
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_bookdem:/var/lib/postgresql/data

  app_node:
    build: .
    container_name: app_node
    ports:
      - 5000:5000
    env_file:
      - .env
    working_dir: /usr/src/bookdem
    volumes:
      - /usr/src/node_modules
      - ./src:/usr/src/bookdem
      - ./prisma:/usr/src/bookdem/prisma

    entrypoint: dockerize -wait tcp://pg_bookdem:5432 -timeout 30s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - pg_bookdem

volumes:
  pg_bookdem: